version: '3'
services:
  database:
    image: mariadb
    container_name: database
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: contrasenaROOT
      MYSQL_DATABASE: db_usuario
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contrasena
    restart: unless-stopped
  phpmyadmin:
    depends_on:
      - database
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8081:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: contrasenaROOT
  webserver:
    build:
      context: .
      dockerfile: custom_nginx.dockerfile
    image: nginx:latest
    container_name: nginx
    volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d/
     - ./html:/var/www
    ports:
     - "8080:80"
    links:
        - php
    restart: unless-stopped
  php:
    image: php:7.4-fpm
    container_name: php
    working_dir: /var/www
    volumes:
     - ./html:/var/www
    user: "101:101"
    restart: unless-stopped
